name: test-auth

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install and Test
        run: |
          cd auth
          npm install
          npm run test:ci
